version: '3.8'

services:
  evolution-api:
    build: .
    container_name: evolution_api
    restart: always
    ports:
      - "8085:8085"
    env_file:
      - .env
    environment:
      - SERVER_PORT=8085
      - DATABASE_ENABLED=true
      - DATABASE_PROVIDER=postgresql
      - DATABASE_CONNECTION_URI=postgresql://postgres:postgres@evolution_postgres:5432/evolution_db?schema=public
      - CACHE_REDIS_ENABLED=true
      - CACHE_REDIS_URI=redis://evolution_redis:6379/0
    depends_on:
      - evolution_postgres
      - evolution_redis
    volumes:
      - evolution_instances:/evolution/instances

  evolution_postgres:
    image: postgres:15-alpine
    container_name: evolution_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: evolution_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

  evolution_redis:
    image: redis:7-alpine
    container_name: evolution_redis
    restart: always
    volumes:
      - redis_data:/data

volumes:
  evolution_instances:
  postgres_data:
  redis_data:
