-- AlterTable
ALTER TABLE "AuditConfig" ADD COLUMN "reportType" VARCHAR(20) NOT NULL DEFAULT 'COMPLIANCE';
ALTER TABLE "AuditReport" ADD COLUMN "reportType" VARCHAR(20) NOT NULL DEFAULT 'COMPLIANCE';
